blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/keycloak/keycloak/discussions
    about: Propose new ideas, provide feedback, or ask for help here
  - name: User mailing list
    url: https://groups.google.com/forum/#!forum/keycloak-user
    about: Ask and answer questions here 
  - name: Developer mailing list 
    url: https://groups.google.com/forum/#!forum/keycloak-dev
    about: Propose new features and join in design discussions here
